discodeit:
  storage:
    type: local
    local:
      root-path: ./data/binary

spring:
  application:
    name: discodeit
  jpa:
    database: POSTGRESQL

    properties:
      hibernate:
        format_sql: true
    open-in-view: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace