server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:prod-db-host}:${DB_PORT:5432}/${DB_NAME:discodeit}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:change-me}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info